"use client";

import { useEffect, useState } from "react";

interface Entry {
  id: string;
  description: string;
  fullChars: number;
  briefChars: number;
  reduction: number;
  integrityComplete: boolean;
  sections: {
    decided: number;
    open: number;
    rejected: number;
    verbatim: number;
    files: number;
  };
  judged?: { sameMove: boolean; reasoning: string };
}

interface Scorecard {
  generatedFor: string;
  judged: boolean;
  entries: Entry[];
}

const pct = (n: number) => `${Math.round(n * 100)}%`;

function Pill({ children, tone }: { children: React.ReactNode; tone: string }) {
  return (
    <span className={`inline-block rounded-full px-2.5 py-0.5 text-xs font-medium ${tone}`}>
      {children}
    </span>
  );
}

export default function Home() {
  const [card, setCard] = useState<Scorecard | null>(null);
  const [error, setError] = useState(false);

  useEffect(() => {
    fetch("/scorecard.json")
      .then((r) => (r.ok ? r.json() : Promise.reject()))
      .then(setCard)
      .catch(() => setError(true));
  }, []);

  return (
    <main className="mx-auto max-w-3xl px-6 py-16">
      <header className="mb-12">
        <h1 className="text-4xl font-bold tracking-tight">
          carry<span className="text-accent">bot</span>
        </h1>
        <p className="mt-3 text-lg text-neutral-600 dark:text-neutral-300">
          One click turns a long, messy AI chat into a structured brief:{" "}
          <strong>Decided · Open · Rejected · Verbatim · Files</strong>, that you
          can carry to a fresh chat, another chatbot, or a teammate, losing
          nothing that matters.
        </p>
        <div className="mt-5 flex flex-wrap gap-2">
          <Pill tone="bg-accent/10 text-accent">read from the data layer</Pill>
          <Pill tone="bg-green-500/10 text-green-700 dark:text-green-400">no daily limits</Pill>
          <Pill tone="bg-blue-500/10 text-blue-700 dark:text-blue-400">BYOK · no server</Pill>
          <Pill tone="bg-neutral-500/10 text-neutral-600 dark:text-neutral-300">rejected-with-why</Pill>
        </div>
      </header>

      <section>
        <h2 className="text-2xl font-semibold">The proof</h2>
        <p className="mt-2 text-neutral-600 dark:text-neutral-300">
          Give a fresh model only the brief, and separately the full chat. Ask
          both the same next question. If the brief-only answer makes the same
          next move, the brief kept everything load-bearing. This table is
          generated by the eval harness in the repo.
        </p>

        {error && (
          <p className="mt-6 rounded-lg bg-amber-500/10 p-4 text-sm text-amber-700 dark:text-amber-300">
            No scorecard found yet. Run <code>pnpm eval</code> to generate it.
          </p>
        )}

        {card && (
          <>
            <p className="mt-6 text-sm text-neutral-500">
              Generated for <code>{card.generatedFor}</code> ·{" "}
              {card.judged ? "full same-next-move judgement" : "shape + size report (no key)"}
            </p>
            <div className="mt-4 overflow-hidden rounded-xl border border-neutral-200 dark:border-neutral-700">
              <table className="w-full text-sm">
                <thead className="bg-neutral-100 text-left dark:bg-neutral-800">
                  <tr>
                    <th className="px-4 py-3 font-semibold">Fixture</th>
                    <th className="px-4 py-3 font-semibold">Size</th>
                    <th className="px-4 py-3 font-semibold">D/O/R/V/F</th>
                    <th className="px-4 py-3 font-semibold">Same move?</th>
                  </tr>
                </thead>
                <tbody>
                  {card.entries.map((e) => {
                    const s = e.sections;
                    return (
                      <tr key={e.id} className="border-t border-neutral-200 dark:border-neutral-700">
                        <td className="px-4 py-3">
                          <div className="font-medium">{e.id}</div>
                          <div className="text-xs text-neutral-500">{e.description}</div>
                        </td>
                        <td className="px-4 py-3 whitespace-nowrap">
                          {e.fullChars}→{e.briefChars}
                          <span className="ml-1 text-green-600">−{pct(e.reduction)}</span>
                        </td>
                        <td className="px-4 py-3 whitespace-nowrap tabular-nums">
                          {s.decided}/{s.open}/{s.rejected}/{s.verbatim}/{s.files}
                        </td>
                        <td className="px-4 py-3">
                          {e.judged ? (
                            e.judged.sameMove ? (
                              <Pill tone="bg-green-500/10 text-green-700 dark:text-green-400">✅ yes</Pill>
                            ) : (
                              <Pill tone="bg-red-500/10 text-red-700 dark:text-red-400">❌ no</Pill>
                            )
                          ) : (
                            <span className="text-neutral-400">n/a</span>
                          )}
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </>
        )}
      </section>

      <footer className="mt-16 border-t border-neutral-200 pt-6 text-sm text-neutral-500 dark:border-neutral-700">
        Your chat is read locally and sent only to the AI provider you chose with
        your own key. No accounts, no limits, no middleman server.
      </footer>
    </main>
  );
}
